#!/bin/bash
echo "\e[5;97mANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANO" 
echo -e "\e[5;97mNODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANOD" 
echo -e "\e[5;97mODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE" 
echo -e "\e[5;33mDE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE." 
echo -e "\e[5;33mE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.T"
echo -e "\e[5;33m.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TE"
echo -e "\e[5;33mTEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEA\e[m"
