#!/bin/bash
echo -e "\[5;33mANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANO" 
echo -e "\[5;33mNODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANOD" 
echo -e "\[5;33mODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE" 
echo -e "\[5;33mDE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE." 
echo -e "\[5;33mE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.T"
echo -e "\[5;33m.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TE"
echo -e "\[5;33mTEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEAM|ANODE.TEA\e[m"
